# Generated by Django 4.0.3 on 2022-03-16 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('mileage', models.IntegerField()),
                ('manufacturer', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inoperative', 'Inoperative')], default='active', max_length=12)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
