# Generated by Django 4.0.3 on 2022-03-19 03:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('unit', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('mileage', models.IntegerField()),
                ('manufacturer', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inoperative', 'Inoperative')], default='active', max_length=12)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Miles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage', models.IntegerField()),
                ('date_created', models.DateField(default=datetime.date.today)),
                ('difference', models.IntegerField(null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miles', to='mileage_tracker.vehicle')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
