# Generated by Django 4.0.3 on 2022-03-16 14:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mileage_tracker', '0002_remove_vehicle_id_vehicle_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='MileageAndDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mil', models.IntegerField()),
                ('date_created', models.DateField(default=datetime.date.today, unique=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mileage_tracker.vehicle')),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
    ]
